# Generated by Django 5.2.8 on 2026-07-07 08:43

from django.db import migrations, models

# 組立部品（BAITEN STAND を構成する家具・筐体類）の部品コードプレフィックス
ASSEMBLY_PREFIXES = {
    "ARM", "DARM", "OARM",  # アーム類
    "BLEG", "BTBL", "MTBL",  # 脚・天板
    "ENC", "MBX",  # エンクロージャ・Box
    "PM",  # ラック・カート・シェルフ（設置台）
}

# 周辺部品のプレフィックス（LTEルータ・ケーブル・保守用キーボード・ネットワークカメラ）
PERIPHERAL_PREFIXES = {"LTE", "MCBL", "KEY", "NCAM"}

# 主要部品とみなすカテゴリ（PC/モニター/バーコード/決済端末/カメラ）
MAIN_CATEGORIES = {"PC", "MONITOR", "BARCODE", "PAYMENT", "CAMERA"}


def classify(part) -> str:
    """既存部品を part_group へ分類する（プレフィックス優先→カテゴリ）"""
    prefix = part.part_code.split("-")[0]
    if prefix in ASSEMBLY_PREFIXES:
        return "ASSEMBLY"
    if prefix in PERIPHERAL_PREFIXES or part.category == "CABLE":
        return "PERIPHERAL"
    if part.category in MAIN_CATEGORIES:
        return "MAIN"
    return "OTHER"


def set_part_groups(apps, schema_editor):
    PartMaster = apps.get_model("bom", "PartMaster")
    for part in PartMaster.objects.all():
        group = classify(part)
        if part.part_group != group:
            part.part_group = group
            part.save(update_fields=["part_group"])


def unset_part_groups(apps, schema_editor):
    # AddField が巻き戻る際に列ごと消えるため何もしない
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partmaster',
            name='part_group',
            field=models.CharField(choices=[('MAIN', '主要部品'), ('PERIPHERAL', '周辺部品'), ('ASSEMBLY', '組立部品'), ('OTHER', 'その他')], default='OTHER', help_text='主要部品/周辺部品/組立部品/その他 の大分類', max_length=20, verbose_name='部品グループ'),
        ),
        migrations.RunPython(set_part_groups, unset_part_groups),
    ]
