# Generated by Django 5.2.8 on 2026-07-07 10:54

import django.db.models.deletion
from django.db import migrations, models

# 既存モデルコード → グレード初期値
CODE_TO_GRADE = {
    "BSTAND-AI": "AI",
    "BSTAND-MINI": "Mini",
    "BSTAND-UNKNOWN": "不明",
}


def seed_family_and_grades(apps, schema_editor):
    ProductFamily = apps.get_model("bom", "ProductFamily")
    ProductModel = apps.get_model("bom", "ProductModel")

    baiten, _ = ProductFamily.objects.get_or_create(
        name="BAITEN STAND",
        defaults={"description": "無人決済機 BAITEN STAND シリーズ"},
    )
    for model in ProductModel.objects.all():
        model.family = baiten
        model.grade = CODE_TO_GRADE.get(model.code)
        model.save(update_fields=["family", "grade"])


def unseed(apps, schema_editor):
    # 逆方向は列削除で消えるため何もしない
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0003_partcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ファミリ名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': '製品ファミリ',
                'verbose_name_plural': '製品ファミリ',
                'db_table': 'product_family',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='grade',
            field=models.CharField(blank=True, help_text='例: AI / Mini / Pro', max_length=100, null=True, verbose_name='グレード'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='variation',
            field=models.CharField(blank=True, help_text='例: 8GB / LTE / 屋外用', max_length=100, null=True, verbose_name='バリエーション'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_models', to='bom.productfamily', verbose_name='製品ファミリ'),
        ),
            migrations.RunPython(seed_family_and_grades, unseed),
    ]
