# Generated by Django 5.2.8 on 2026-07-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_productfamily_productmodel_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partmaster',
            name='used_in_ai',
        ),
        migrations.RemoveField(
            model_name='partmaster',
            name='used_in_mini',
        ),
    ]
