# Generated by Django 5.2.8 on 2026-07-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0005_remove_partmaster_used_in_ai_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bssset',
            options={'ordering': ['-created_at'], 'verbose_name': '製品セット', 'verbose_name_plural': '製品セット'},
        ),
        migrations.AlterModelOptions(
            name='bsssetcomponent',
            options={'ordering': ['bss_set', 'role'], 'verbose_name': '製品セット構成部品', 'verbose_name_plural': '製品セット構成部品'},
        ),
        migrations.AlterModelOptions(
            name='bsssetconfig',
            options={'ordering': ['bss_set', 'config_group', 'key'], 'verbose_name': '製品セット設定', 'verbose_name_plural': '製品セット設定'},
        ),
        migrations.AddField(
            model_name='customersite',
            name='country',
            field=models.CharField(default='JP', help_text='ISO 3166-1 alpha-2（例: JP / US）', max_length=2, verbose_name='国コード'),
        ),
        migrations.AlterField(
            model_name='bsssetcomponent',
            name='bss_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='bom.bssset', verbose_name='製品セット'),
        ),
        migrations.AlterField(
            model_name='bsssetconfig',
            name='bss_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='bom.bssset', verbose_name='製品セット'),
        ),
        migrations.AlterField(
            model_name='deployevent',
            name='bss_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deploy_events', to='bom.bssset', verbose_name='製品セット'),
        ),
        migrations.AlterField(
            model_name='maintenanceevent',
            name='bss_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_events', to='bom.bssset', verbose_name='製品セット'),
        ),
    ]
