# Generated by Django 5.2.8 on 2026-07-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0006_alter_bssset_options_alter_bsssetcomponent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product_families',
            field=models.ManyToManyField(blank=True, help_text='契約・商談段階など設置実績がない関連の手動登録。設置実績は自動導出される', related_name='customers', to='bom.productfamily', verbose_name='取扱製品ファミリ（手動）'),
        ),
    ]
