# Generated by Django 5.2.8 on 2026-07-08 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0007_customer_product_families'),
    ]

    operations = [
        migrations.AddField(
            model_name='partunit',
            name='storage_site',
            field=models.ForeignKey(blank=True, help_text='未搭載時の物理的な保管場所。倉庫は lifecycle_status=拠点(BASE) の拠点を使う', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_units', to='bom.customersite', verbose_name='保管先倉庫'),
        ),
    ]
