# Generated by Django 5.2.8 on 2026-07-09 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0008_partunit_storage_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(help_text='例: BSTAND-SW, RISCV-FW', max_length=50, unique=True, verbose_name='ソフトウェアコード')),
                ('name', models.CharField(max_length=200, verbose_name='ソフトウェア名')),
                ('kind', models.CharField(choices=[('STACK', 'アプリスタック'), ('FIRMWARE', 'ファームウェア'), ('OS', 'OS'), ('OTHER', 'その他')], default='STACK', max_length=20, verbose_name='種別')),
                ('vendor', models.CharField(blank=True, max_length=100, null=True, verbose_name='提供元')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
            ],
            options={
                'verbose_name': 'ソフトウェアマスタ',
                'verbose_name_plural': 'ソフトウェアマスタ',
                'db_table': 'software_master',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('version', models.CharField(help_text='例: 2.3.1', max_length=50, verbose_name='バージョン')),
                ('status', models.CharField(choices=[('RELEASED', 'リリース'), ('BETA', 'ベータ'), ('DEPRECATED', '非推奨')], default='RELEASED', max_length=20, verbose_name='状態')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='リリース日')),
                ('artifact_ref', models.CharField(blank=True, help_text='git tag / commit hash / 配布URL 等', max_length=300, null=True, verbose_name='アーティファクト参照')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='リリースノート')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='bom.softwaremaster', verbose_name='ソフトウェア')),
            ],
            options={
                'verbose_name': 'ソフトウェアバージョン',
                'verbose_name_plural': 'ソフトウェアバージョン',
                'db_table': 'software_version',
                'ordering': ['-release_date', '-created_at'],
                'unique_together': {('software', 'version')},
            },
        ),
    ]
